const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Physics,
		C3.Plugins.Audio,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.NinePatch,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Globals,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.Flash,
		C3.Plugins.advert,
		C3.Plugins.Azerion_Integration_SDK,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Behaviors.ppstudio_parabolictween_beh,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Globals.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Azerion_Integration_SDK.Cnds.IsAdPlaying,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.advert.Cnds.OnRewardedCancelled,
		C3.Plugins.advert.Cnds.OnRewardedFailedToLoad,
		C3.Plugins.advert.Cnds.OnRewardedComplete,
		C3.Plugins.advert.Acts.CreateRewarded,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Globals.Acts.AddInstanceVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Globals.Exps.GetVariablesAsJSON,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Globals.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Touch.Exps.X,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.ppstudio_parabolictween_beh.Acts.TweenParabola,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Globals.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Physics.Cnds.IsImmovable,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.ppstudio_parabolictween_beh.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Azerion_Integration_SDK.Acts.InitializeSDK,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.JavaScriptInEvents.Azerionintegration_Event3_Act6,
		C3.JavaScriptInEvents.Azerionintegration_Event3_Act7,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnLoadProgress,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnLoadStart,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnLoadComplete,
		C3.Plugins.Azerion_Integration_SDK.Acts.AddListeners,
		C3.JavaScriptInEvents.Azerionintegration_Event8_Act1,
		C3.JavaScriptInEvents.Azerionintegration_Event8_Act2,
		C3.JavaScriptInEvents.Azerionintegration_Event9_Act1,
		C3.Plugins.Azerion_Integration_SDK.Acts.PreloadAd,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Azerion_Integration_SDK.Acts.ShowInterstitialAd,
		C3.Plugins.Azerion_Integration_SDK.Acts.ShowRewardedAd,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnGameStart,
		C3.Plugins.Azerion_Integration_SDK.Acts.OnGameEnd,
		C3.Plugins.Azerion_Integration_SDK.Acts.SendScoreEvent,
		C3.JavaScriptInEvents.Azerionintegration_Event26_Act2,
		C3.JavaScriptInEvents.Azerionintegration_Event28_Act2,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Globals.Acts.LoadVariables,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.TiledBg.Exps.Width
	];
};
self.C3_JsPropNameTable = [
	{Lvl: 0},
	{picked_to_destroy: 0},
	{picked_to_UP: 0},
	{uids: 0},
	{waitMerge: 0},
	{coll: 0},
	{spawn: 0},
	{Item: 0},
	{Arrow: 0},
	{Touch: 0},
	{Physics: 0},
	{zwall: 0},
	{current_uid: 0},
	{aframe: 0},
	{matchChecker: 0},
	{Audio: 0},
	{Tween: 0},
	{Timer: 0},
	{Spawner: 0},
	{Limit: 0},
	{zzz9patchtarget: 0},
	{zzobjs: 0},
	{Btn_Settings: 0},
	{zscreen: 0},
	{Rotate: 0},
	{prtcl_win_obj: 0},
	{Text_: 0},
	{Sine: 0},
	{LimitRed: 0},
	{zlimit: 0},
	{au_bgm: 0},
	{au_sfx: 0},
	{item_min: 0},
	{item_max: 0},
	{Level_Real: 0},
	{Level_Show: 0},
	{boost_Swap: 0},
	{boost_Remove: 0},
	{boost_UpLvl: 0},
	{LoseTime: 0},
	{Money: 0},
	{unlockedJuice: 0},
	{VARS: 0},
	{AJAX: 0},
	{Arr_Level: 0},
	{Next: 0},
	{Btn_End: 0},
	{sf_Btn: 0},
	{"9patch": 0},
	{BtnCloseBoost: 0},
	{Btn_Bgm: 0},
	{Btn_Sfx: 0},
	{Btn_Menu: 0},
	{Btn_Continue: 0},
	{LocalStorage: 0},
	{Background: 0},
	{sf_Level: 0},
	{Fade: 0},
	{zscreen2start: 0},
	{bgtargetstart: 0},
	{Btn_Continue2: 0},
	{zsorts: 0},
	{yposs: 0},
	{Juice: 0},
	{spJuice: 0},
	{sf_Btn_PlayGame: 0},
	{zzjuces: 0},
	{sf_Level2: 0},
	{Btn_Endless: 0},
	{Particles: 0},
	{"9patch2": 0},
	{zzzendico: 0},
	{Btn_Menu2: 0},
	{Flash: 0},
	{sf_Boost_info: 0},
	{boost_arrow: 0},
	{Boost_Swap: 0},
	{Boost_UpLvl: 0},
	{Boost_Remove: 0},
	{Btn_Close: 0},
	{uidsell: 0},
	{boost_popup: 0},
	{boost_popupapply: 0},
	{boost_add_swap: 0},
	{MobileAdvert: 0},
	{sf_boost_swap: 0},
	{sf_boost_uplvl: 0},
	{sf_boost_remove: 0},
	{boost_add_uplvl: 0},
	{boost_add_remove: 0},
	{prtcl_up: 0},
	{fx_circl: 0},
	{addtoboost: 0},
	{bonus: 0},
	{Particles2: 0},
	{CoinMoveTo: 0},
	{sf_Money: 0},
	{prtcl_coin: 0},
	{sf_Price: 0},
	{Btn_Buy: 0},
	{buy_popup: 0},
	{Btn_Close2: 0},
	{fx_ray1: 0},
	{NewJuiceUnlocked: 0},
	{gamename: 0},
	{zmmenuobjs: 0},
	{AzIntegrationPlugin: 0},
	{Browser: 0},
	{loading_bg: 0},
	{loading_bar: 0},
	{NoAdText: 0},
	{ITEMS: 0},
	{zotheritem: 0},
	{JUICEs: 0},
	{ParabolicTween: 0},
	{BONUSADD: 0},
	{COINS: 0},
	{UNL_JUICE: 0},
	{SAVENAME: 0},
	{reward_curr: 0},
	{boost_up_used: 0},
	{lose_timer: 0},
	{next: 0},
	{curr: 0},
	{pX: 0},
	{pY: 0},
	{HasFocus: 0},
	{rewardAvailable: 0},
	{IsWatchAd: 0},
	{PREROLL_ENABLED: 0},
	{AllAssetsLoaded: 0},
	{HasFocusAPI: 0},
	{progress: 0},
	{cScore: 0},
	{currentScore: 0},
	{cummulativeScore: 0},
	{levelNr: 0},
	{LoadProg: 0}
];

self.InstanceType = {
	Item: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	zwall: class extends self.ITiledBackgroundInstance {},
	matchChecker: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Spawner: class extends self.ISpriteInstance {},
	Limit: class extends self.ITiledBackgroundInstance {},
	zzz9patchtarget: class extends self.I9PatchInstance {},
	zzobjs: class extends self.ISpriteInstance {},
	Btn_Settings: class extends self.ISpriteInstance {},
	zscreen: class extends self.ITiledBackgroundInstance {},
	prtcl_win_obj: class extends self.ISpriteInstance {},
	Text_: class extends self.ISpriteInstance {},
	LimitRed: class extends self.ITiledBackgroundInstance {},
	zlimit: class extends self.ISpriteInstance {},
	VARS: class extends C3.Plugins.Globals.Instance {},
	AJAX: class extends self.IInstance {},
	Arr_Level: class extends self.IArrayInstance {},
	Next: class extends self.ISpriteInstance {},
	Btn_End: class extends self.ISpriteInstance {},
	sf_Btn: class extends self.ISpriteFontInstance {},
	_9patch: class extends self.I9PatchInstance {},
	BtnCloseBoost: class extends self.ISpriteInstance {},
	Btn_Bgm: class extends self.ISpriteInstance {},
	Btn_Sfx: class extends self.ISpriteInstance {},
	Btn_Menu: class extends self.ISpriteInstance {},
	Btn_Continue: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Background: class extends self.ISpriteInstance {},
	sf_Level: class extends self.ISpriteFontInstance {},
	zscreen2start: class extends self.ITiledBackgroundInstance {},
	bgtargetstart: class extends self.I9PatchInstance {},
	Btn_Continue2: class extends self.ISpriteInstance {},
	Juice: class extends self.ISpriteInstance {},
	spJuice: class extends self.ISpriteInstance {},
	sf_Btn_PlayGame: class extends self.ISpriteFontInstance {},
	zzjuces: class extends self.ISpriteInstance {},
	sf_Level2: class extends self.ISpriteFontInstance {},
	Btn_Endless: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	_9patch2: class extends self.I9PatchInstance {},
	zzzendico: class extends self.ISpriteInstance {},
	Btn_Menu2: class extends self.ISpriteInstance {},
	sf_Boost_info: class extends self.ISpriteFontInstance {},
	boost_arrow: class extends self.ISpriteInstance {},
	Boost_Swap: class extends self.ISpriteInstance {},
	Boost_UpLvl: class extends self.ISpriteInstance {},
	Boost_Remove: class extends self.ISpriteInstance {},
	Btn_Close: class extends self.ISpriteInstance {},
	boost_popup: class extends self.ISpriteInstance {},
	boost_popupapply: class extends self.ISpriteInstance {},
	boost_add_swap: class extends self.ISpriteInstance {},
	MobileAdvert: class extends self.IInstance {},
	sf_boost_swap: class extends self.ISpriteFontInstance {},
	sf_boost_uplvl: class extends self.ISpriteFontInstance {},
	sf_boost_remove: class extends self.ISpriteFontInstance {},
	boost_add_uplvl: class extends self.ISpriteInstance {},
	boost_add_remove: class extends self.ISpriteInstance {},
	prtcl_up: class extends self.IParticlesInstance {},
	fx_circl: class extends self.ISpriteInstance {},
	bonus: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	CoinMoveTo: class extends self.ISpriteInstance {},
	sf_Money: class extends self.ISpriteFontInstance {},
	prtcl_coin: class extends self.IParticlesInstance {},
	sf_Price: class extends self.ISpriteFontInstance {},
	Btn_Buy: class extends self.ISpriteInstance {},
	buy_popup: class extends self.ISpriteInstance {},
	Btn_Close2: class extends self.ISpriteInstance {},
	unlockedJuice: class extends self.ISpriteInstance {},
	fx_ray1: class extends self.ISpriteInstance {},
	NewJuiceUnlocked: class extends self.ISpriteInstance {},
	gamename: class extends self.ISpriteInstance {},
	zmmenuobjs: class extends self.ISpriteInstance {},
	AzIntegrationPlugin: class extends C3.Plugins.Azerion_Integration_SDK.Instance {},
	Browser: class extends self.IInstance {},
	loading_bg: class extends self.ISpriteInstance {},
	loading_bar: class extends self.ITiledBackgroundInstance {},
	NoAdText: class extends self.ITextInstance {},
	ITEMS: class extends self.ISpriteInstance {},
	zotheritem: class extends self.ISpriteInstance {},
	JUICEs: class extends self.ISpriteInstance {},
	BONUSADD: class extends self.ISpriteInstance {},
	zsorts: class extends self.ISpriteInstance {},
	COINS: class extends self.ISpriteInstance {},
	UNL_JUICE: class extends self.ISpriteInstance {}
}